service: devnet-faucet-backend
runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

# Define the entry point for your application
entrypoint: yarn start

# Environment variables (replace with your actual values or secrets)
env_variables:
  POSTGRES_STRING: ${{ secrets.POSTGRES_STRING }}

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

# Network configuration
network:
  instance_tag: solana-devnet-faucet-backend
  name: default